# Stats 21 - HW 3

# Kayla Tjenalooi

Homework copyright Miles Chen. Problems have been adapted from the exercises in Think Python 2nd Ed by Allen B. Downey.

The questions have been entered into this document. You will modify the document by entering your code.

Make sure you run the cell so the requested output is visible. Export it as an HTML file and then print to PDF.

**Homework is an opportunity to practice coding and to practice problem solving.**

**Doing exercises is where you will do most of your learning.**

**Using AI or copying someone else's solutions takes away your learning opportunities. It is also academic dishonesty.**

## Reading

- Chapter 10 - Dictionaries
- Chapter 12 - Tuples
- Chapter 13 - Files

Please keep up with the reading. The chapters are short.

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.1

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

Write a function that reads the words in `words.txt` and stores them as keys in a dictionary. It doesn't matter what the values are. Then you can use the `in` operator as a fast way to check whether a string is in the dictionary.

In [5]:
def make_word_dict():
    t = {}
    fin = open('words.txt')
    for line in fin:
        word = line.strip()
        t[word] = None
    return t

word_dict = make_word_dict()

In [6]:

"hello" in word_dict

True

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.4

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

In HW2 Exercise 10.7, you created a function called `has_duplicates()`. It takes a list as a parameter and returns `True` if there is any object that appears more than once in the list.

Use a dictionary to write a faster, simpler version of `has_duplicates()`.

In [10]:
def has_duplicates(t):
    seen = {}
    for item in t:
        if item in seen:
            return True
        seen[item] = True
    return False

In [11]:
has_duplicates(['a','b','b','c'])

True

In [12]:
has_duplicates(['a','b','c','a'])

True

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.5

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

A Caesar cipher is a weak form of encryption that involves 'rotating' each letter by a fixed number of places. To rotate a letter means to shift it through the alphabet, wrapping around to the beginning if necessary. "A" rotated by 3 is "D". "Z" rotated by 1 is "A".

Two words are "rotate pairs" if you can rotate one of them and get the other. For example, "cheer" rotated by 7 is "jolly".

Write a script that reads in the wordlist `words.txt` and finds all the rotate pairs of words that are 5 letters or longer.

One function that could be helpful is the function `ord()` which converts a character to a numeric code. Keep in mind that numeric codes for uppercase and lowercase letters are different.

Some hints:

- you can write helper functions, such as a function that will rotate a letter by a certain number and/or another function that will rotate a word by a number of letters
- to keep your script running quickly, you should use the wordlist dictionary from exercise 11.1

In [65]:
# write your code here.

#rotate the letter 
def rotate_letter(letter, n):
    if letter.islower():
        return chr((ord(letter) - ord('a') + n) % 26 + ord('a'))
    elif letter.isupper():
        return chr((ord(letter) - ord('A') + n) % 26 + ord('A'))
    return letter

#rotate the entire word 
def rotate_word(word, n):
    result = ""
    for c in word:
        result += rotate_letter(c, n)
    return result


def find_rotate_pairs(words):
    pairs = []
    for word in words:
        if len(word) < 5:
            continue
        for n in range(1, 26):
            rotated = rotate_word(word, n)
            if rotated in words:
                pairs.append((word, rotated, n))
    return pairs

words = make_word_dict() 
sum = 0

for word, rotated, n in find_rotate_pairs(words):
    print(f'"{word}" rotated by {n} is "{rotated}"')
    sum += 1

print(sum)

"abjurer" rotated by 13 is "nowhere"
"adder" rotated by 1 is "beefs"
"ahull" rotated by 6 is "gnarr"
"alkyd" rotated by 4 is "epoch"
"alula" rotated by 19 is "tenet"
"ambit" rotated by 18 is "setal"
"anteed" rotated by 1 is "bouffe"
"aptly" rotated by 19 is "timer"
"arena" rotated by 17 is "river"
"baiza" rotated by 18 is "tsars"
"banjo" rotated by 4 is "ferns"
"beefs" rotated by 25 is "adder"
"benni" rotated by 16 is "ruddy"
"biffs" rotated by 6 is "holly"
"bolls" rotated by 6 is "hurry"
"bombyx" rotated by 6 is "hushed"
"bouffe" rotated by 25 is "anteed"
"bourg" rotated by 20 is "viola"
"buffi" rotated by 6 is "hallo"
"bulls" rotated by 6 is "harry"
"bunny" rotated by 17 is "sleep"
"butyl" rotated by 6 is "hazer"
"chain" rotated by 6 is "ingot"
"cheer" rotated by 7 is "jolly"
"clasp" rotated by 15 is "raphe"
"cogon" rotated by 16 is "sewed"
"commy" rotated by 16 is "secco"
"corky" rotated by 20 is "wiles"
"craal" rotated by 13 is "penny"
"credo" rotated by 16 is "shute"
"creel" rotat

In [14]:
has_duplicates(['a','b','b','c'])

True

### Modified Exercise based on Think Python 2ed. Chap 12, Section 10, Exercise 12.2

<https://greenteapress.com/thinkpython2/html/thinkpython2013.html>

Write a program that reads a word list from a file (see Section 9.1) and finds all the sets of words that are anagrams.

After finding all anagram sets, print the list of all anagram sets that have 6 or more entries in it.

Here is an example of what the output might look like:

~~~
['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']
['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced']
...
~~~

Hint:

First traverse the entire wordlist to build a dictionary that maps from a collection of letters to a list of words that can be spelled with those letters. The question is, how can you represent the collection of letters in a way that can be used as a key? i.e. The word "eat" and the word "tea" should be in a list associated with a key ('a','e','t').

In [ ]:
def find_anagrams(words):
    anagram_map = {}
    for word in words:
        key = tuple(sorted(word))
        if key not in anagram_map:
            anagram_map[key] = []
        anagram_map[key].append(word)
    return anagram_map

words = make_word_dict()
anagram_map = find_anagrams(words)

for group in anagram_map.values():
    if len(group) >= 6:
        print(group)

['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']
['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced']
['aiders', 'deairs', 'irades', 'raised', 'redias', 'resaid']
['airts', 'astir', 'sitar', 'stair', 'stria', 'tarsi']
['alert', 'alter', 'artel', 'later', 'ratel', 'taler']
['alerting', 'altering', 'integral', 'relating', 'tanglier', 'triangle']
['alerts', 'alters', 'artels', 'estral', 'laster', 'ratels', 'salter', 'slater', 'staler', 'stelar', 'talers']
['alevin', 'alvine', 'valine', 'veinal', 'venial', 'vineal']
['algins', 'aligns', 'lasing', 'liangs', 'ligans', 'lingas', 'signal']
['aliens', 'alines', 'elains', 'lianes', 'saline', 'silane']
['aligners', 'engrails', 'nargiles', 'realigns', 'signaler', 'slangier']
['amens', 'manes', 'manse', 'means', 'mensa', 'names', 'nemas']
['anestri', 'nastier', 'ratines', 'retains', 'retinas', 'retsina', 'stainer', 'stearin']
['angriest', 'astringe', 'ganister

### NumPy Exercises

For the following exercises, be sure to print the desired output. You will not receive credit for problems that do not print the desired output.

Some of these exercises will require the use of functions in numpy that may not have been covered in class. Look up documentation on how to use them. I always recommend checking the official reference at https://numpy.org/doc/stable/reference/index.html 

In [86]:
import numpy as np
rng = np.random.default_rng(seed = 1)

#### Exercise NP.1:

Task: Create an array `b` of 10 random integers selected between 0-99

Desired output: `[47 51 75 95  3 14 82 94 24 31]` of course yours might be different

In [87]:
b = np.random.randint(1, 100, 10)

b

array([92, 64, 35, 39, 90, 26, 20, 80, 84,  8])

#### NP.1b:

Task: reverse the elements in `b`. Hint: Try slicing the array, but backwards

In [85]:
b[::-1]

array([26,  3, 87, 12, 79, 14, 43, 83, 48, 98])

#### NP.2a:

Task: Create an array `c` of 1000 random values selected from a normal distribution centered at 100 with sd = 15, rounded to 1 decimal place. Print only the first 10 values.

Desired output: `[ 92.1  83.9 113.   65.5 126.2  88.6 104.8  96.3 121.9  69.1]` of course your values may be different

In [95]:
#fix this 

c = rng.normal(100, 15, 100).round(1)

print(c[:10])

[127.4 130.3  84.  105.6  89.9  99.6  81.  128.   85.5  95.6]


#### NP.2b:

Perform a Shapiro-Wilk test to see if the values in c come from a normal distribution. Report the p-value and appropriate conclusion.

Look up `scipy.stats.shapiro` for usage and details.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html

In [96]:
from scipy import stats

test_stat, p = stats.shapiro(c)
print(f"p-value: {p:.4f}")

if p > 0.05:
    print("Fail to reject H0: data is consistent with a normal distribution.")
else:
    print("Reject H0: data does not appear to be normally distributed.")

p-value: 0.0703
Fail to reject H0: data is consistent with a normal distribution.


#### NP.2c:

Identify and print the values in `c` that are more than 3 standard deviations from the mean of `c`. Report the proportion of values that are more than 3 sd from the mean.

Desired output: `[ 54.1 ... 148.3 ]`

`0.32 of the values are beyond 3 sd from the mean.`

In [98]:
mean = np.mean(c)
sd = np.std(c)

outliers = c[np.abs(c - mean) > 3 * sd]
print("Outliers:", outliers)
print(f"Proportion: {len(outliers) / len(c):.4f}")

Outliers: [146.5]
Proportion: 0.0100


#### NP.3:

Task: Make a 3x3 identity matrix called `I3`

Desired output: 

~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
~~~

In [35]:
I3 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 1]])

#### NP.4a:

Task: Make a 10x10 array of values 1 to 100. Call it X

Desired output: 

~~~
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
 ~~~

In [38]:
X = np.arange(1, 101).reshape(10, 10)

print(X)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


#### NP.4b:

Task: Make a copy of X, call it Y (1 line). Replace all values in Y that are not squares with 0 (1 line). see `numpy.isin()`

Desired output: 

~~~
[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
...
 [  0   0   0   0   0   0   0   0   0 100]]
 ~~~

In [39]:
Y = X.copy()
Y[~np.isin(Y, [i**2 for i in range(1, 11)])] = 0

print(Y)

[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
 [  0   0   0   0   0  36   0   0   0   0]
 [  0   0   0   0   0   0   0   0  49   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  64   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 81   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 100]]


#### NP.5:

Task: Use `np.tile()` to tile a 2x2 diagonal matrix of integers to make a checkerboard pattern. Call the matrix `checkers`

Desired output: 

~~~
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
 ~~~

In [ ]:
checker_tile = np.array([[1, 0],
                 [0, 1]])

checkers = np.tile(checker_tile, (4, 4))

#### NP.6:

Task: convert the values in `f_temp` from Farenheit to celsius. The conversion is subtract 32, then multiply by 5/9. Round to 1 decimal place.

Desired output: 

~~~
[[21.1 21.7 22.2 22.8 23.3 23.9]
 ...
 [34.4 35.  35.6 36.1 36.7 37.2]]
~~~

In [67]:
# do not modify
f_temp  = np.arange(70,100).reshape((5,6))

print(f_temp)

[[70 71 72 73 74 75]
 [76 77 78 79 80 81]
 [82 83 84 85 86 87]
 [88 89 90 91 92 93]
 [94 95 96 97 98 99]]


In [68]:
c_temp = np.round((f_temp - 32) * 5/9, 1)

print(c_temp)

[[21.1 21.7 22.2 22.8 23.3 23.9]
 [24.4 25.  25.6 26.1 26.7 27.2]
 [27.8 28.3 28.9 29.4 30.  30.6]
 [31.1 31.7 32.2 32.8 33.3 33.9]
 [34.4 35.  35.6 36.1 36.7 37.2]]


#### NP.7:

Task: Convert values in the matrix `x` into z-scores by column, call it matrix `z`. That is: each column should have a mean of 0 and std of 1. (subtract the column mean, and divide by the column std). (not required, but see if you can do this in one line)

Print the column means and column std to show that they have been standardized.

Desired output: 

~~~
[[ 0.41148428  1.04307072 -1.43031951]
 [-0.34069129 -1.14825432 -0.77270135]
...
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]
 
[-1.16573418e-16  7.77156117e-17  1.44328993e-16]
[1. 1. 1.]
~~~

In [45]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 30).reshape(10,3)

In [ ]:
z = (x - x.mean(axis=0)) / x.std(axis=0)

print(z)
print(z.mean(axis=0))
print(z.std(axis=0))


[[ 0.41148428  1.04307072 -1.43031951]
 [-0.34069129 -1.14825432 -0.77270135]
 [-1.00437562 -1.26512499  0.46033272]
 [ 1.34064235  1.36446505  0.50143385]
 [-1.13711249  0.92620005  1.85777132]
 [ 1.07516861 -1.38199565  0.87134407]
 [ 0.19025617 -0.85607765  0.13152363]
 [ 1.38488797  0.60480571 -0.77270135]
 [-1.53532308  0.42949971 -1.34811724]
 [-0.38493691  0.28341137  0.50143385]]
[-1.16573418e-16  7.77156117e-17  1.44328993e-16]
[1. 1. 1.]


#### NP.8:

Task: Convert values in the matrix `x` into scaled values from 0 to 10. That is take each column and scale values linearly so that the largest value is 10, and the smallest value in the column is 0. Round results to 2 decimal places. Call the result `y`

(Not required, but see if you can do the calculations in one line.)

Desired output: 

~~~
[[0.67 0.88 0.  ]
 [0.41 0.09 0.2 ]
 ...
 [0.   0.66 0.02]
 [0.39 0.61 0.59]]
 ~~~

In [79]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 30).reshape(10,3)

In [80]:
y = ((x - x.min(axis=0)) / (x - x.min(axis=0)).max(axis=0) * 10).round(2)

#different than desired output because we want values 0-10 not the values 0-1 in desired output 
print(y)

[[ 6.67  8.83  0.  ]
 [ 4.09  0.85  2.  ]
 [ 1.82  0.43  5.75]
 [ 9.85 10.    5.88]
 [ 1.36  8.4  10.  ]
 [ 8.94  0.    7.  ]
 [ 5.91  1.91  4.75]
 [10.    7.23  2.  ]
 [ 0.    6.6   0.25]
 [ 3.94  6.06  5.88]]


#### NP.9:

Task: Replace all NaN values in the matrix `x` with 0.

Desired output: 

~~~
[[76. 83. 12.]
 [59.  8.  0.]
 [44.  0. 58.]
 [ 0. 94. 59.]]
~~~

In [53]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 12).reshape(4,3).astype('float')
row = np.array([1, 2, 3])
col = np.array([2, 1, 0])
x[row, col] = np.nan

In [54]:
x[np.isnan(x)] = 0
print(x)

[[76. 83. 12.]
 [59.  8.  0.]
 [44.  0. 58.]
 [ 0. 94. 59.]]
